server:
  servlet:
    context-path: /tk
  port: 9000
type: Framework
name: Spring-Boot ${type}
my:
  messageValue: ${random.int(10,1500)} # This is prod profile
  # random.int(10,1500) 9 to 1499 inclusive if we need 10 and 1500 random.int*10,1500*
find:
  randomObj: ${random.uuid}
spring:
  profiles:
    active: Prod
  datasource:
    continue-on-error: true
#https://www.baeldung.com/spring-boot-actuator-enable-endpoints
#https://www.baeldung.com/spring-boot-actuators

#heath metrics using actuators
#Default built-in end points -https://docs.spring.io/spring-boot/docs/current/reference/html/production-ready-features.html#production-ready-endpoints
#include: info,health,metrics,loggers,beans,mappings,configprops,conditions,env  OR '*'
#Below though all are enabled, we disabled only loggers

management:
  security:
    enabled: false
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
    loggers:
      enabled: false

# Define program argument as --spring.profiles.active=Prod in this commandline has preference 
test:
   name-print: Hello this is from test.name_print 
   name:
     test: Hello this is from test.name.test

tk:
  projectName: ThanujProject